# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('sex', models.CharField(choices=[('M', '男性'), ('F', '女性'), ('S', '保密')], max_length=8, verbose_name='性别')),
                ('icon', models.ImageField(upload_to='', verbose_name='头像')),
            ],
        ),
    ]
