# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-29 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plt_icon',
            field=models.URLField(default='', verbose_name='第三方平台url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女'), ('保密', '保密')], max_length=8, verbose_name='性别'),
        ),
    ]
